
'use server';

/**
 * @fileOverview A routing agent that determines the user's intent from a voice query
 * and calls the appropriate specialized agent or provides a general response.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';
import { findSchemes } from './government-schemes-flow';
import { marketAnalysis } from './market-analysis-flow';
import { recommendCrops } from './crop-recommender-flow';
import { languages } from '@/lib/i18n';
import { MarketAnalysisInputSchema } from '../schemas/market-analysis-schemas';
import { CropRecommenderInputSchema } from '../schemas/crop-recommender-schemas';
import { GovernmentSchemesInputSchema } from '../schemas/government-schemes-schemas';
import { getCurrentUser } from '@/lib/firebase/server-auth';

const RouterInputSchema = z.object({
  query: z.string().describe("The user's transcribed voice query."),
  language: z.string().optional().describe('The language for the response.'),
});

const RouterOutputSchema = z.object({
  agentResponse: z.string().describe('The final textual response generated by the selected agent, which will be converted to speech.'),
  actionTaken: z.string().describe("A brief description of which agent was called or what action was taken. e.g., 'Called Market Analysis Agent' or 'Could not determine intent'."),
  agentUsed: z.enum(['marketAnalysis', 'cropRecommender', 'cropDiagnosis', 'irrigationScheduler', 'governmentSchemes', 'fallback']).optional(),
  sourceLink: z.string().url().optional().describe("A link to the agent's page for more details.")
});

// Define tools that the router can call
const marketAnalysisTool = ai.defineTool(
  {
    name: 'marketAnalysis',
    description: 'Use for questions about crop prices, market trends, and commodity markets. Keywords: price, rate, market, mandi, cost, sell.',
    inputSchema: MarketAnalysisInputSchema.pick({ commodity: true, location: true, market: true, query: true }),
    outputSchema: z.any(),
  },
  async (input) => marketAnalysis(input)
);

const cropRecommenderTool = ai.defineTool(
  {
    name: 'cropRecommender',
    description: 'Use for questions about which crops to plant, what to grow, or crop selection, especially if a location is mentioned. Keywords: grow, plant, sow, cultivate, which crop.',
    inputSchema: CropRecommenderInputSchema.pick({ location: true, lastCropGrown: true, termPeriod: true, userGoal: true }),
    outputSchema: z.any(),
  },
  async (input) => recommendCrops(input)
);

const governmentSchemesTool = ai.defineTool(
  {
    name: 'governmentSchemes',
    description: 'Use for questions about government support, subsidies, or agricultural schemes. Keywords: scheme, government, subsidy, loan, help, PM Kisan, bima, insurance.',
    inputSchema: GovernmentSchemesInputSchema,
    outputSchema: z.any(),
  },
  async (input) => findSchemes(input)
);

export async function routeVoiceQuery(input: z.infer<typeof RouterInputSchema>): Promise<z.infer<typeof RouterOutputSchema>> {
  return voiceAgentRouterFlow(input);
}

const voiceAgentRouterFlow = ai.defineFlow(
  {
    name: 'voiceAgentRouterFlow',
    inputSchema: RouterInputSchema,
    outputSchema: RouterOutputSchema,
  },
  async (input) => {
    const user = await getCurrentUser();
    const currentLanguageName = languages.find(l => l.code === input.language)?.name.split(' ')[0] || 'English';

    // Step 1: Use the AI to determine which tool to call based on the user's query.
    const { toolRequest, text } = await ai.generate({
      model: 'googleai/gemini-2.0-flash',
      prompt: `You are an expert AI routing agent for NeerVaani, a farming assistant. Your job is to understand a farmer's spoken query and decide which specialized tool is the most appropriate to use to answer their question.
      
      The user's profile name is ${user?.name || 'Farmer'}.
      
      The user's query is: "${input.query}".
      
      - If the user provides specific details (like a location for crop recommendations, or a commodity name for market prices), call the appropriate tool.
      - If the query is general (e.g., "suggest a crop", "how to farm better"), do not call a tool. Instead, provide a helpful, general conversational response.`,
      tools: [marketAnalysisTool, cropRecommenderTool, governmentSchemesTool],
      config: { temperature: 0 },
    });

    // Step 2: If the AI decided to call a tool because the query was specific enough
    if (toolRequest) {
        console.log(`Calling tool: ${toolRequest.name}`);
        
        try {
            // Step 3: Execute the chosen tool.
            const toolResponse = await toolRequest.run();

            // Step 4: Use the AI again to generate a natural language response from the tool's structured output.
            const { output: finalResponse } = await ai.generate({
                model: 'googleai/gemini-2.0-flash',
                prompt: `You are NeerVaani, a helpful AI assistant for farmers. A user asked: "${input.query}". You have used a tool called '${toolRequest.name}' and received the following JSON data.
                
                JSON Data:
                \`\`\`json
                ${JSON.stringify(toolResponse, null, 2)}
                \`\`\`

                Your task is to synthesize this data into a simple, clear, and detailed response for the farmer. Address them directly. Explain your findings in a conversational way. 
                - If you have crop recommendations, list the top 3 with their key financial details (yield, cost, profit).
                - If you found schemes, mention the most relevant one and its primary benefit.
                - If you have market analysis, state the key recommendation clearly.
                
                The response must be in: ${currentLanguageName}.`,
                output: {
                    schema: z.object({
                        summary: z.string().describe("A detailed, conversational summary of the data."),
                        recommendation: z.string().optional().describe("A key recommendation if applicable."),
                    })
                }
            });
            
            if (!finalResponse) {
                throw new Error("The AI failed to generate a summary for the tool's output.");
            }

            const agentResponse = `${finalResponse.summary} ${finalResponse.recommendation || ''} To get more detailed information, kindly use the full ${toolRequest.name.replace(/([A-Z])/g, ' $1').trim()} agent in the NeerHub.`;
            const agentUsed = toolRequest.name as z.infer<typeof RouterOutputSchema>['agentUsed'];

            return {
                agentResponse,
                actionTaken: `Called ${toolRequest.name} tool.`,
                agentUsed: agentUsed,
                sourceLink: `/neerhub#${agentUsed}`
            };
        } catch (error: any) {
            console.error(`Error executing tool ${toolRequest.name}:`, error);
            // Formulate a user-friendly error message
             const userFriendlyError = `I'm sorry, I encountered a problem with the ${toolRequest.name.replace(/([A-Z])/g, ' $1')} tool. Please try rephrasing your question or check the NeerHub for more details.`;

            return {
                agentResponse: userFriendlyError,
                actionTaken: `Error in ${toolRequest.name} tool.`,
                agentUsed: 'fallback'
            };
        }
    }
    
    // Step 5: Fallback for general queries where no specific tool is called
    const { text: fallbackResponse } = await ai.generate({
          prompt: `You are a friendly and helpful farmer's assistant called NeerVaani. The user said: "${input.query}". Respond conversationally and helpfully in ${currentLanguageName}. 
          
          - If the user asks for a crop recommendation without giving a location, provide a general list of 3-4 profitable crops in India (like tomatoes, onions, wheat, and marigolds) and briefly mention why they are good choices (high demand, multiple harvests, etc.).
          - If the query seems to be about a feature you don't support via voice (like crop diagnosis from an image), guide them to the correct tool in the NeerHub.
          - For all other general questions, provide a helpful, concise answer.`,
          model: 'googleai/gemini-2.0-flash',
    });
    const agentResponse = fallbackResponse ?? "Hello! How can I help you with your farm today?";

    return {
      agentResponse,
      actionTaken: 'Conversational fallback for a general query.',
      agentUsed: 'fallback'
    };
  }
);

    